### ISSUE TITLE
add hyprcursor

### ISSUE THREAD

**Issue by rice-cracker-dev** [hyprland-community/awesome-hyprland#82]
add hyprcursor frfr: https://github.com/hyprwm/hyprcursor

**Comment by BackHDLP** [comment]
I don't think this belongs here, since it's a library implementing a cursor format. the only tool in there is the tool to create a cursor, which I don't believe an average user needs.

cc @Heyian

**Comment by Heyian** [comment]
@BackHDLP 
I agree that the utility isn't for the average user but so are the language bindings... At the top of the readme, it states : _"Awesome list for Hyprland, that includes useful tools **<ins>and libraries</ins>** that either work or are designed for Hyprland!"_, that's why I was inclined to add it.

Maybe it's simply in the wrong category?

I don't think this is a must though, while I personaly still think it belongs in the list, I don't feel strongly about it.

**Comment by BackHDLP** [comment]
hyprcursor feels lower level than the language bindings. The language bindings are like an api, people use apis all the time to interact with whatever through whatever language. hyprcursor is a library, used by Hyprland (and maybe KDE at some point :eyes:), a user doesn't need it unless they want to make something that renders its own cursor (which is really unlikely). 
You could argue that hyprcursor-util should be here, since it's used to make the cursors, but we don't have any other cursor generating or similar tools here, and it's not standalone.

> At the top of the readme, it states : "Awesome list for Hyprland, that includes useful tools and libraries that either work or are designed for Hyprland!",

this is a real me not being able to read moment lol

> Maybe it's simply in the wrong category?

that definitely

**Comment by yavko** [comment]
I'm honestly not sure what to do, but since it seems like more people want it than don't, I'll merge any PRs

**Comment by Heyian** [comment]
Should we just make a DEV Tools category? I gotta make a correction to my PR to make it less vague(I totally agree), I'll try to put it in the right category at the same time.

**Comment by yavko** [comment]
You can keep it where it is, just make the description, more, uhm, *descriptive*.

**Comment by DonPiotr** [comment]
Maybe a little bit of topic but it would be nice to have here hyprcursor themes.

**Comment by rice-cracker-dev** [comment]
> Maybe a little bit of topic but it would be nice to have here hyprcursor themes.

good idea

**Comment by yavko** [comment]
forgor to close 💀
